name: Manual Run Deploy 3-Tier

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag'
        required: true
        default: 'BD-2023'
      tier:
        description: 'App Tier to deploy'
        required: true
        type: choice
        options:
          - frontend
          - backend
          - database
        default: 'backend'

env:
  REGISTRY: docker.io
  IMAGE_NAME: jogaraoreddy/${{ github.event.inputs.tier }}-app 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

     Tar # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ github.event.inputs.tier }}
        load: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}

    # Security Scanning Step 1: Docker Scout
    - name: Docker Scout Scan
      uses: docker/scout-action@v1
      with:
        command: quickview,cves
        image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}
        only-severities: critical,high
        exit-code: true 

    # Security Scanning Step 2: Trivy
    - name: Run Trivy Scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}'
        format: 'table'
        exit-code: '1' 
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ github.event.inputs.tier }}
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}

    # SSH to Bastion Server and Deploy to EKS
    - name: SSH to Bastion and Deploy via Helm
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }} # ◄ Change '22' to this
        script: |
          # 1. Target your specific EKS cluster (Modify cluster name/region)
          aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster
          
          # 2. Update Helm Release
          helm upgrade --install ${{ github.event.inputs.tier }}-release ./charts/${{ github.event.inputs.tier }} \
            --namespace 3-tier-app \
            --set image.tag=${{ github.event.inputs.image_tag }} \
            --wait
